- name: Demo on conditions
  hosts: localhost
  tasks:
    - name: Print Apple Price
      ansible.builtin.debug:
        msg: Apple Price is - 1$

    - name: Print Orange price
      ansible.builtin.debug:
        msg: Orange price is - 2$